name: phpstan

on:
  push:

jobs:
  laravel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        tools: composer:v2
    - name: Resolve dependencies in laravel
      run: cd laravel && composer install --no-progress --prefer-dist --optimize-autoloader
    - name: Run phpstan in laravel
      run: cd laravel && ./vendor/bin/phpstan --memory-limit=1G analyse --error-format=github | sed -e 's/ file=/ file=laravel\//' | ../.github/cs2pr.php

  vanilla:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run phpstan in laravel
        run: cd vanilla && docker run -v `pwd`:/app -w /app ghcr.io/phpstan/phpstan analyse --error-format=github | sed -e 's/ file=/ file=vanilla\//' | ../.github/cs2pr.php
