name: phpstan

on:
  pull_request:

jobs:
  laravel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        tools: composer:v2, cs2pr
    - name: Resolve dependencies in laravel
      run: cd laravel && composer install --no-progress --prefer-dist --optimize-autoloader
    - name: Run phpstan in laravel
      run: cd laravel && ./vendor/bin/phpstan --memory-limit=1G analyse --error-format=checkstyle | sed -e 's/<file name="/<file name="laravel\//' | cs2pr

  vanilla:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run phpstan in laravel
        run: cd vanilla && docker run -v `pwd`:/app -w /app ghcr.io/phpstan/phpstan analyse
